language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get --no-install-recommends install darcs libgtksourceview-3.0-dev
  - mkdir vendor
  - cd vendor
  - darcs get --lazy http://patch-tag.com/r/hamish/gtk2hs
  - cabal install ./gtk2hs/tools
  - cd ..
install:
  - cabal install cabal-meta cabal-src
  - cabal-meta install -fgtk3 --force-reinstalls
notifications:
  irc:
    channels: "irc.freenode.net#leksah"
  email: true
